name: CI
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: 'windows-2019'
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: arm
            goarm: 5
          - arch: arm
            goarm: 7
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0' # Currently an error with go1.16 for rune convrsion. Update this once fixed.
      - run: go build ./...
        env:
          GO111MODULE: off
  test:
    runs-on: 'windows-2019'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0' # Currently an error with go1.16 for rune convrsion. Update this once fixed.
      - run: go test ./...
        env:
          GO111MODULE: off